#----------------------------------------------------------------
# Generated CMake target import file for configuration "RelWithDebInfo".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "LLVMSupport" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSupport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSupport PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSupport.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSupport )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSupport "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSupport.a" )

# Import target "LLVMTableGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMTableGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMTableGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTableGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMTableGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMTableGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTableGen.a" )

# Import target "llvm-tblgen" for configuration "RelWithDebInfo"
set_property(TARGET llvm-tblgen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-tblgen PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-tblgen"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-tblgen )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-tblgen "${_IMPORT_PREFIX}/bin/llvm-tblgen" )

# Import target "LLVMCore" for configuration "RelWithDebInfo"
set_property(TARGET LLVMCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCore.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMCore )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMCore "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCore.a" )

# Import target "LLVMIRReader" for configuration "RelWithDebInfo"
set_property(TARGET LLVMIRReader APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMIRReader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMIRReader.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMIRReader )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMIRReader "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMIRReader.a" )

# Import target "LLVMCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCodeGen.a" )

# Import target "LLVMSelectionDAG" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSelectionDAG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSelectionDAG PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSelectionDAG.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSelectionDAG )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSelectionDAG "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSelectionDAG.a" )

# Import target "LLVMAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAsmPrinter.a" )

# Import target "LLVMMIRParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMIRParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMIRParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMIRParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMIRParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMIRParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMIRParser.a" )

# Import target "LLVMBitReader" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBitReader APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBitReader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBitReader.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBitReader )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBitReader "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBitReader.a" )

# Import target "LLVMBitWriter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBitWriter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBitWriter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBitWriter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBitWriter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBitWriter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBitWriter.a" )

# Import target "LLVMTransformUtils" for configuration "RelWithDebInfo"
set_property(TARGET LLVMTransformUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMTransformUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTransformUtils.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMTransformUtils )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMTransformUtils "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTransformUtils.a" )

# Import target "LLVMInstrumentation" for configuration "RelWithDebInfo"
set_property(TARGET LLVMInstrumentation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMInstrumentation PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInstrumentation.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMInstrumentation )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMInstrumentation "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInstrumentation.a" )

# Import target "LLVMInstCombine" for configuration "RelWithDebInfo"
set_property(TARGET LLVMInstCombine APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMInstCombine PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInstCombine.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMInstCombine )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMInstCombine "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInstCombine.a" )

# Import target "LLVMScalarOpts" for configuration "RelWithDebInfo"
set_property(TARGET LLVMScalarOpts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMScalarOpts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMScalarOpts.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMScalarOpts )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMScalarOpts "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMScalarOpts.a" )

# Import target "LLVMipo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMipo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMipo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMipo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMipo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMipo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMipo.a" )

# Import target "LLVMVectorize" for configuration "RelWithDebInfo"
set_property(TARGET LLVMVectorize APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMVectorize PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMVectorize.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMVectorize )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMVectorize "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMVectorize.a" )

# Import target "LLVMHello" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHello APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHello PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/LLVMHello.so"
  IMPORTED_NO_SONAME_RELWITHDEBINFO "TRUE"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHello )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHello "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/LLVMHello.so" )

# Import target "LLVMObjCARCOpts" for configuration "RelWithDebInfo"
set_property(TARGET LLVMObjCARCOpts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMObjCARCOpts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMObjCARCOpts.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMObjCARCOpts )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMObjCARCOpts "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMObjCARCOpts.a" )

# Import target "LLVMLinker" for configuration "RelWithDebInfo"
set_property(TARGET LLVMLinker APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMLinker PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLinker.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMLinker )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMLinker "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLinker.a" )

# Import target "LLVMAnalysis" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAnalysis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAnalysis PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAnalysis.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAnalysis )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAnalysis "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAnalysis.a" )

# Import target "LLVMLTO" for configuration "RelWithDebInfo"
set_property(TARGET LLVMLTO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMLTO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLTO.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMLTO )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMLTO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLTO.a" )

# Import target "LLVMMC" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMC PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMC.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMC )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMC "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMC.a" )

# Import target "LLVMMCParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMCParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMCParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMCParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMCParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCParser.a" )

# Import target "LLVMMCDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMCDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMCDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMCDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMCDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCDisassembler.a" )

# Import target "LLVMObject" for configuration "RelWithDebInfo"
set_property(TARGET LLVMObject APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMObject PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMObject.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMObject )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMObject "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMObject.a" )

# Import target "LLVMOption" for configuration "RelWithDebInfo"
set_property(TARGET LLVMOption APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMOption PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMOption.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMOption )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMOption "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMOption.a" )

# Import target "LLVMDebugInfoCodeView" for configuration "RelWithDebInfo"
set_property(TARGET LLVMDebugInfoCodeView APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMDebugInfoCodeView PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoCodeView.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMDebugInfoCodeView )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMDebugInfoCodeView "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoCodeView.a" )

# Import target "LLVMDebugInfoDWARF" for configuration "RelWithDebInfo"
set_property(TARGET LLVMDebugInfoDWARF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMDebugInfoDWARF PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoDWARF.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMDebugInfoDWARF )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMDebugInfoDWARF "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoDWARF.a" )

# Import target "LLVMDebugInfoPDB" for configuration "RelWithDebInfo"
set_property(TARGET LLVMDebugInfoPDB APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMDebugInfoPDB PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoPDB.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMDebugInfoPDB )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMDebugInfoPDB "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMDebugInfoPDB.a" )

# Import target "LLVMSymbolize" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSymbolize APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSymbolize PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSymbolize.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSymbolize )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSymbolize "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSymbolize.a" )

# Import target "LLVMExecutionEngine" for configuration "RelWithDebInfo"
set_property(TARGET LLVMExecutionEngine APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMExecutionEngine PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMExecutionEngine.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMExecutionEngine )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMExecutionEngine "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMExecutionEngine.a" )

# Import target "LLVMInterpreter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMInterpreter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMInterpreter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInterpreter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMInterpreter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMInterpreter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMInterpreter.a" )

# Import target "LLVMMCJIT" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMCJIT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMCJIT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCJIT.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMCJIT )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMCJIT "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMCJIT.a" )

# Import target "LLVMOrcJIT" for configuration "RelWithDebInfo"
set_property(TARGET LLVMOrcJIT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMOrcJIT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMOrcJIT.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMOrcJIT )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMOrcJIT "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMOrcJIT.a" )

# Import target "LLVMRuntimeDyld" for configuration "RelWithDebInfo"
set_property(TARGET LLVMRuntimeDyld APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMRuntimeDyld PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMRuntimeDyld.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMRuntimeDyld )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMRuntimeDyld "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMRuntimeDyld.a" )

# Import target "LLVMTarget" for configuration "RelWithDebInfo"
set_property(TARGET LLVMTarget APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMTarget PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTarget.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMTarget )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMTarget "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMTarget.a" )

# Import target "LLVMAArch64CodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64CodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64CodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64CodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64CodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64CodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64CodeGen.a" )

# Import target "LLVMAArch64Info" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64Info APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64Info PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Info.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64Info )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64Info "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Info.a" )

# Import target "LLVMAArch64AsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64AsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64AsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64AsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64AsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64AsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64AsmParser.a" )

# Import target "LLVMAArch64Disassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64Disassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64Disassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Disassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64Disassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64Disassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Disassembler.a" )

# Import target "LLVMAArch64AsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64AsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64AsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64AsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64AsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64AsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64AsmPrinter.a" )

# Import target "LLVMAArch64Desc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64Desc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64Desc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Desc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64Desc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64Desc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Desc.a" )

# Import target "LLVMAArch64Utils" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAArch64Utils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAArch64Utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Utils.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAArch64Utils )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAArch64Utils "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAArch64Utils.a" )

# Import target "LLVMAMDGPUCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUCodeGen.a" )

# Import target "LLVMAMDGPUAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUAsmParser.a" )

# Import target "LLVMAMDGPUAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUAsmPrinter.a" )

# Import target "LLVMAMDGPUInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUInfo.a" )

# Import target "LLVMAMDGPUDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUDesc.a" )

# Import target "LLVMAMDGPUUtils" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAMDGPUUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAMDGPUUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUUtils.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAMDGPUUtils )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAMDGPUUtils "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAMDGPUUtils.a" )

# Import target "LLVMARMCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMCodeGen.a" )

# Import target "LLVMARMInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMInfo.a" )

# Import target "LLVMARMAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMAsmParser.a" )

# Import target "LLVMARMDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMDisassembler.a" )

# Import target "LLVMARMAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMAsmPrinter.a" )

# Import target "LLVMARMDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMARMDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMARMDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMARMDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMARMDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMARMDesc.a" )

# Import target "LLVMBPFCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBPFCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBPFCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBPFCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBPFCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFCodeGen.a" )

# Import target "LLVMBPFAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBPFAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBPFAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBPFAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBPFAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFAsmPrinter.a" )

# Import target "LLVMBPFInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBPFInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBPFInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBPFInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBPFInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFInfo.a" )

# Import target "LLVMBPFDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMBPFDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMBPFDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMBPFDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMBPFDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMBPFDesc.a" )

# Import target "LLVMCppBackendCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMCppBackendCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMCppBackendCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCppBackendCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMCppBackendCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMCppBackendCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCppBackendCodeGen.a" )

# Import target "LLVMCppBackendInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMCppBackendInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMCppBackendInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCppBackendInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMCppBackendInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMCppBackendInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMCppBackendInfo.a" )

# Import target "LLVMHexagonCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHexagonCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHexagonCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHexagonCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHexagonCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonCodeGen.a" )

# Import target "LLVMHexagonAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHexagonAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHexagonAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHexagonAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHexagonAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonAsmParser.a" )

# Import target "LLVMHexagonInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHexagonInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHexagonInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHexagonInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHexagonInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonInfo.a" )

# Import target "LLVMHexagonDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHexagonDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHexagonDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHexagonDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHexagonDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonDesc.a" )

# Import target "LLVMHexagonDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMHexagonDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMHexagonDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMHexagonDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMHexagonDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMHexagonDisassembler.a" )

# Import target "LLVMMipsCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsCodeGen.a" )

# Import target "LLVMMipsAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsAsmPrinter.a" )

# Import target "LLVMMipsDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsDisassembler.a" )

# Import target "LLVMMipsInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsInfo.a" )

# Import target "LLVMMipsDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsDesc.a" )

# Import target "LLVMMipsAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMipsAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMipsAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMipsAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMipsAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMipsAsmParser.a" )

# Import target "LLVMMSP430CodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMSP430CodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMSP430CodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430CodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMSP430CodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMSP430CodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430CodeGen.a" )

# Import target "LLVMMSP430AsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMSP430AsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMSP430AsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430AsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMSP430AsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMSP430AsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430AsmPrinter.a" )

# Import target "LLVMMSP430Info" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMSP430Info APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMSP430Info PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430Info.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMSP430Info )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMSP430Info "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430Info.a" )

# Import target "LLVMMSP430Desc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMMSP430Desc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMMSP430Desc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430Desc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMMSP430Desc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMMSP430Desc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMMSP430Desc.a" )

# Import target "LLVMNVPTXCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMNVPTXCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMNVPTXCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMNVPTXCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMNVPTXCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXCodeGen.a" )

# Import target "LLVMNVPTXInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMNVPTXInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMNVPTXInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMNVPTXInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMNVPTXInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXInfo.a" )

# Import target "LLVMNVPTXAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMNVPTXAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMNVPTXAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMNVPTXAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMNVPTXAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXAsmPrinter.a" )

# Import target "LLVMNVPTXDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMNVPTXDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMNVPTXDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMNVPTXDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMNVPTXDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMNVPTXDesc.a" )

# Import target "LLVMPowerPCCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCCodeGen.a" )

# Import target "LLVMPowerPCAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCAsmParser.a" )

# Import target "LLVMPowerPCDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCDisassembler.a" )

# Import target "LLVMPowerPCAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCAsmPrinter.a" )

# Import target "LLVMPowerPCInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCInfo.a" )

# Import target "LLVMPowerPCDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPowerPCDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPowerPCDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPowerPCDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPowerPCDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPowerPCDesc.a" )

# Import target "LLVMSparcCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcCodeGen.a" )

# Import target "LLVMSparcInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcInfo.a" )

# Import target "LLVMSparcDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcDesc.a" )

# Import target "LLVMSparcAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcAsmPrinter.a" )

# Import target "LLVMSparcAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcAsmParser.a" )

# Import target "LLVMSparcDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSparcDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSparcDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSparcDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSparcDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSparcDisassembler.a" )

# Import target "LLVMSystemZCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZCodeGen.a" )

# Import target "LLVMSystemZAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZAsmParser.a" )

# Import target "LLVMSystemZDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZDisassembler.a" )

# Import target "LLVMSystemZAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZAsmPrinter.a" )

# Import target "LLVMSystemZInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZInfo.a" )

# Import target "LLVMSystemZDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMSystemZDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMSystemZDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMSystemZDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMSystemZDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMSystemZDesc.a" )

# Import target "LLVMX86CodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86CodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86CodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86CodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86CodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86CodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86CodeGen.a" )

# Import target "LLVMX86AsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86AsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86AsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86AsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86AsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86AsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86AsmParser.a" )

# Import target "LLVMX86Disassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86Disassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86Disassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Disassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86Disassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86Disassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Disassembler.a" )

# Import target "LLVMX86AsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86AsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86AsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86AsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86AsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86AsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86AsmPrinter.a" )

# Import target "LLVMX86Desc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86Desc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86Desc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Desc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86Desc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86Desc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Desc.a" )

# Import target "LLVMX86Info" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86Info APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86Info PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Info.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86Info )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86Info "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Info.a" )

# Import target "LLVMX86Utils" for configuration "RelWithDebInfo"
set_property(TARGET LLVMX86Utils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMX86Utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Utils.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMX86Utils )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMX86Utils "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMX86Utils.a" )

# Import target "LLVMXCoreCodeGen" for configuration "RelWithDebInfo"
set_property(TARGET LLVMXCoreCodeGen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMXCoreCodeGen PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreCodeGen.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMXCoreCodeGen )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMXCoreCodeGen "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreCodeGen.a" )

# Import target "LLVMXCoreDisassembler" for configuration "RelWithDebInfo"
set_property(TARGET LLVMXCoreDisassembler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMXCoreDisassembler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreDisassembler.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMXCoreDisassembler )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMXCoreDisassembler "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreDisassembler.a" )

# Import target "LLVMXCoreAsmPrinter" for configuration "RelWithDebInfo"
set_property(TARGET LLVMXCoreAsmPrinter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMXCoreAsmPrinter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreAsmPrinter.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMXCoreAsmPrinter )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMXCoreAsmPrinter "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreAsmPrinter.a" )

# Import target "LLVMXCoreInfo" for configuration "RelWithDebInfo"
set_property(TARGET LLVMXCoreInfo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMXCoreInfo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreInfo.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMXCoreInfo )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMXCoreInfo "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreInfo.a" )

# Import target "LLVMXCoreDesc" for configuration "RelWithDebInfo"
set_property(TARGET LLVMXCoreDesc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMXCoreDesc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreDesc.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMXCoreDesc )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMXCoreDesc "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMXCoreDesc.a" )

# Import target "LLVMAsmParser" for configuration "RelWithDebInfo"
set_property(TARGET LLVMAsmParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMAsmParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAsmParser.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMAsmParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMAsmParser "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMAsmParser.a" )

# Import target "LLVMLineEditor" for configuration "RelWithDebInfo"
set_property(TARGET LLVMLineEditor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMLineEditor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLineEditor.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMLineEditor )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMLineEditor "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLineEditor.a" )

# Import target "LLVMProfileData" for configuration "RelWithDebInfo"
set_property(TARGET LLVMProfileData APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMProfileData PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMProfileData.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMProfileData )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMProfileData "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMProfileData.a" )

# Import target "LLVMPasses" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPasses APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPasses PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPasses.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPasses )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPasses "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMPasses.a" )

# Import target "LLVMLibDriver" for configuration "RelWithDebInfo"
set_property(TARGET LLVMLibDriver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMLibDriver PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLibDriver.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMLibDriver )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMLibDriver "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVMLibDriver.a" )

if(_CFATI_FALSE)
# Import target "PollyISL" for configuration "RelWithDebInfo"
set_property(TARGET PollyISL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PollyISL PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libPollyISL.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS PollyISL )
list(APPEND _IMPORT_CHECK_FILES_FOR_PollyISL "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libPollyISL.a" )

# Import target "Polly" for configuration "RelWithDebInfo"
set_property(TARGET Polly APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Polly PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libPolly.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS Polly )
list(APPEND _IMPORT_CHECK_FILES_FOR_Polly "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libPolly.a" )
endif(_CFATI_FALSE)

# Import target "LLVMPolly" for configuration "RelWithDebInfo"
set_property(TARGET LLVMPolly APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVMPolly PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/LLVMPolly.so"
  IMPORTED_NO_SONAME_RELWITHDEBINFO "TRUE"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVMPolly )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVMPolly "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/LLVMPolly.so" )

# Import target "LTO" for configuration "RelWithDebInfo"
set_property(TARGET LTO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LTO PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLTO.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libLTO.so"
  )

list(APPEND _IMPORT_CHECK_TARGETS LTO )
list(APPEND _IMPORT_CHECK_FILES_FOR_LTO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLTO.so" )

# Import target "llvm-ar" for configuration "RelWithDebInfo"
set_property(TARGET llvm-ar APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-ar PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-ar"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-ar )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-ar "${_IMPORT_PREFIX}/bin/llvm-ar" )

# Import target "llvm-config" for configuration "RelWithDebInfo"
set_property(TARGET llvm-config APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-config PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-config"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-config )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-config "${_IMPORT_PREFIX}/bin/llvm-config" )

# Import target "llvm-profdata" for configuration "RelWithDebInfo"
set_property(TARGET llvm-profdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-profdata PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-profdata-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-profdata )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-profdata "${_IMPORT_PREFIX}/bin/llvm-profdata-${_CFATI_LLVM_VER}" )

# Import target "llvm-size" for configuration "RelWithDebInfo"
set_property(TARGET llvm-size APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-size PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-size"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-size )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-size "${_IMPORT_PREFIX}/bin/llvm-size" )

# Import target "llvm-dis" for configuration "RelWithDebInfo"
set_property(TARGET llvm-dis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-dis PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-dis"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-dis )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-dis "${_IMPORT_PREFIX}/bin/llvm-dis" )

# Import target "llvm-extract" for configuration "RelWithDebInfo"
set_property(TARGET llvm-extract APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-extract PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-extract"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-extract )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-extract "${_IMPORT_PREFIX}/bin/llvm-extract" )

# Import target "verify-uselistorder" for configuration "RelWithDebInfo"
set_property(TARGET verify-uselistorder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(verify-uselistorder PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/verify-uselistorder"
  )

list(APPEND _IMPORT_CHECK_TARGETS verify-uselistorder )
list(APPEND _IMPORT_CHECK_FILES_FOR_verify-uselistorder "${_IMPORT_PREFIX}/bin/verify-uselistorder" )

# Import target "lli" for configuration "RelWithDebInfo"
set_property(TARGET lli APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lli PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/lli"
  )

list(APPEND _IMPORT_CHECK_TARGETS lli )
list(APPEND _IMPORT_CHECK_FILES_FOR_lli "${_IMPORT_PREFIX}/bin/lli" )

# Import target "llvm-dsymutil" for configuration "RelWithDebInfo"
set_property(TARGET llvm-dsymutil APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-dsymutil PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-dsymutil-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-dsymutil )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-dsymutil "${_IMPORT_PREFIX}/bin/llvm-dsymutil-${_CFATI_LLVM_VER}" )

# Import target "BugpointPasses" for configuration "RelWithDebInfo"
set_property(TARGET BugpointPasses APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(BugpointPasses PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/BugpointPasses.so"
  IMPORTED_NO_SONAME_RELWITHDEBINFO "TRUE"
  )

list(APPEND _IMPORT_CHECK_TARGETS BugpointPasses )
list(APPEND _IMPORT_CHECK_FILES_FOR_BugpointPasses "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/BugpointPasses.so" )

# Import target "llvm-cxxdump" for configuration "RelWithDebInfo"
set_property(TARGET llvm-cxxdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-cxxdump PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-cxxdump-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-cxxdump )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-cxxdump "${_IMPORT_PREFIX}/bin/llvm-cxxdump-${_CFATI_LLVM_VER}" )

# Import target "llvm-symbolizer" for configuration "RelWithDebInfo"
set_property(TARGET llvm-symbolizer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-symbolizer PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-symbolizer-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-symbolizer )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-symbolizer "${_IMPORT_PREFIX}/bin/llvm-symbolizer-${_CFATI_LLVM_VER}" )

# Import target "obj2yaml" for configuration "RelWithDebInfo"
set_property(TARGET obj2yaml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(obj2yaml PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/obj2yaml"
  )

list(APPEND _IMPORT_CHECK_TARGETS obj2yaml )
list(APPEND _IMPORT_CHECK_FILES_FOR_obj2yaml "${_IMPORT_PREFIX}/bin/obj2yaml" )

# Import target "llvm-c-test" for configuration "RelWithDebInfo"
set_property(TARGET llvm-c-test APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-c-test PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-c-test-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-c-test )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-c-test "${_IMPORT_PREFIX}/bin/llvm-c-test-${_CFATI_LLVM_VER}" )

# Import target "yaml2obj" for configuration "RelWithDebInfo"
set_property(TARGET yaml2obj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(yaml2obj PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/yaml2obj"
  )

list(APPEND _IMPORT_CHECK_TARGETS yaml2obj )
list(APPEND _IMPORT_CHECK_FILES_FOR_yaml2obj "${_IMPORT_PREFIX}/bin/yaml2obj" )

# Import target "llvm-link" for configuration "RelWithDebInfo"
set_property(TARGET llvm-link APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-link PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-link"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-link )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-link "${_IMPORT_PREFIX}/bin/llvm-link" )

# Import target "opt" for configuration "RelWithDebInfo"
set_property(TARGET opt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opt PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/opt"
  )

list(APPEND _IMPORT_CHECK_TARGETS opt )
list(APPEND _IMPORT_CHECK_FILES_FOR_opt "${_IMPORT_PREFIX}/bin/opt" )

# Import target "llvm-readobj" for configuration "RelWithDebInfo"
set_property(TARGET llvm-readobj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-readobj PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-readobj-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-readobj )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-readobj "${_IMPORT_PREFIX}/bin/llvm-readobj-${_CFATI_LLVM_VER}" )

# Import target "llvm-nm" for configuration "RelWithDebInfo"
set_property(TARGET llvm-nm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-nm PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-nm"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-nm )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-nm "${_IMPORT_PREFIX}/bin/llvm-nm" )

# Import target "llvm-rtdyld" for configuration "RelWithDebInfo"
set_property(TARGET llvm-rtdyld APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-rtdyld PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-rtdyld"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-rtdyld )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-rtdyld "${_IMPORT_PREFIX}/bin/llvm-rtdyld" )

if(_CFATI_FALSE)
# Import target "sancov" for configuration "RelWithDebInfo"
set_property(TARGET sancov APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sancov PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/sancov"
  )

list(APPEND _IMPORT_CHECK_TARGETS sancov )
list(APPEND _IMPORT_CHECK_FILES_FOR_sancov "${_IMPORT_PREFIX}/bin/sancov" )
endif(_CFATI_FALSE)

# Import target "llvm-mcmarkup" for configuration "RelWithDebInfo"
set_property(TARGET llvm-mcmarkup APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-mcmarkup PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-mcmarkup-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-mcmarkup )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-mcmarkup "${_IMPORT_PREFIX}/bin/llvm-mcmarkup-${_CFATI_LLVM_VER}" )

# Import target "llvm-lto" for configuration "RelWithDebInfo"
set_property(TARGET llvm-lto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-lto PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-lto-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-lto )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-lto "${_IMPORT_PREFIX}/bin/llvm-lto-${_CFATI_LLVM_VER}" )

# Import target "llvm-objdump" for configuration "RelWithDebInfo"
set_property(TARGET llvm-objdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-objdump PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-objdump"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-objdump )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-objdump "${_IMPORT_PREFIX}/bin/llvm-objdump" )

# Import target "bugpoint" for configuration "RelWithDebInfo"
set_property(TARGET bugpoint APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(bugpoint PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/bugpoint"
  )

list(APPEND _IMPORT_CHECK_TARGETS bugpoint )
list(APPEND _IMPORT_CHECK_FILES_FOR_bugpoint "${_IMPORT_PREFIX}/bin/bugpoint" )

# Import target "llc" for configuration "RelWithDebInfo"
set_property(TARGET llc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llc PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llc"
  )

list(APPEND _IMPORT_CHECK_TARGETS llc )
list(APPEND _IMPORT_CHECK_FILES_FOR_llc "${_IMPORT_PREFIX}/bin/llc" )

# Import target "llvm-dwarfdump" for configuration "RelWithDebInfo"
set_property(TARGET llvm-dwarfdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-dwarfdump PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-dwarfdump"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-dwarfdump )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-dwarfdump "${_IMPORT_PREFIX}/bin/llvm-dwarfdump" )

# Import target "llvm-diff" for configuration "RelWithDebInfo"
set_property(TARGET llvm-diff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-diff PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-diff"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-diff )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-diff "${_IMPORT_PREFIX}/bin/llvm-diff" )

# Import target "llvm-split" for configuration "RelWithDebInfo"
set_property(TARGET llvm-split APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-split PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-split-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-split )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-split "${_IMPORT_PREFIX}/bin/llvm-split-${_CFATI_LLVM_VER}" )

# Import target "llvm-mc" for configuration "RelWithDebInfo"
set_property(TARGET llvm-mc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-mc PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-mc"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-mc )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-mc "${_IMPORT_PREFIX}/bin/llvm-mc" )

# Import target "llvm-stress" for configuration "RelWithDebInfo"
set_property(TARGET llvm-stress APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-stress PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-stress-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-stress )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-stress "${_IMPORT_PREFIX}/bin/llvm-stress-${_CFATI_LLVM_VER}" )

# Import target "llvm-pdbdump" for configuration "RelWithDebInfo"
set_property(TARGET llvm-pdbdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-pdbdump PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-pdbdump-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-pdbdump )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-pdbdump "${_IMPORT_PREFIX}/bin/llvm-pdbdump-${_CFATI_LLVM_VER}" )

# Import target "llvm-cov" for configuration "RelWithDebInfo"
set_property(TARGET llvm-cov APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-cov PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-cov"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-cov )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-cov "${_IMPORT_PREFIX}/bin/llvm-cov" )

# Import target "llvm-as" for configuration "RelWithDebInfo"
set_property(TARGET llvm-as APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-as PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-as"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-as )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-as "${_IMPORT_PREFIX}/bin/llvm-as" )

# Import target "llvm-dwp" for configuration "RelWithDebInfo"
set_property(TARGET llvm-dwp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-dwp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-dwp-${_CFATI_LLVM_VER}"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-dwp )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-dwp "${_IMPORT_PREFIX}/bin/llvm-dwp-${_CFATI_LLVM_VER}" )

# Import target "llvm-bcanalyzer" for configuration "RelWithDebInfo"
set_property(TARGET llvm-bcanalyzer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(llvm-bcanalyzer PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/bin/llvm-bcanalyzer"
  )

list(APPEND _IMPORT_CHECK_TARGETS llvm-bcanalyzer )
list(APPEND _IMPORT_CHECK_FILES_FOR_llvm-bcanalyzer "${_IMPORT_PREFIX}/bin/llvm-bcanalyzer" )

# Import target "LLVM" for configuration "RelWithDebInfo"
set_property(TARGET LLVM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(LLVM PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVM-${_CFATI_LLVM_VER}.0.so.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libLLVM-3.8.so.1"
  )

list(APPEND _IMPORT_CHECK_TARGETS LLVM )
list(APPEND _IMPORT_CHECK_FILES_FOR_LLVM "${_IMPORT_PREFIX}/lib/${_CFATI_LLVM_LIBDIR_SUFFIX}/libLLVM-${_CFATI_LLVM_VER}.0.so.1" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
